Squashed commit of the following:
commit 3bb7587810be672de798f61e1a9eceab1134494a
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Tue Dec 8 22:46:38 2020 +0100

    build: macos: buildosx/create-dmg: Remove debug junk.

commit df78e64d14ce707a6e2d4019232cefb176143bda
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Tue Dec 8 13:20:25 2020 +0100

    ci: macos: Fix bogus dmg-file rw. prefix.

    The applescript fails, and as a side effect the temporary file
    name is used. The dmg looks OK, but the filename needs to handle
    the bad filename until the root cause, the failing applescript, is fixed

commit ba8dbb9062c6922d7cbabbbcbf9afb803d14d8a9
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Tue Dec 8 13:19:46 2020 +0100

    ci: macos: Clean up cache management.

commit 94b3d163ddb8a66ea3fd8ffbe172898f1834c2e9
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Tue Dec 8 12:11:49 2020 +0100

    ci:macos: circleci: Cache homebrew installs.

commit 2b4ece877ded027e0e0d0c7c845a77e52e5e15a7
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Tue Dec 8 11:21:43 2020 +0100

    ci: macos: formatting, debug exit

commit 8daea4ffae5d9ab4b9ab02a291f74dc407b7272c
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Tue Dec 8 10:34:12 2020 +0100

    macos: build: Kepp going on hdiutil errors on Catalina.

    On 10.14, hdiutil does not accept the internet-enable verb any
    more. There is seemingly no alternative. Display a warning but
    keep going when invoking hdituil internet-enable.

commit ceac5bb92258702a549b9b5aa38aef308f1f9649
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Mon Dec 7 22:49:12 2020 +0100

    ci: macos: Update pre-built deps download link, formatting.

commit b3a6131f7667c614d29778781ecea35e6819a486
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Mon Dec 7 22:33:49 2020 +0100

    ci: macos: Update Xcode -> 11.3.0.

commit b7ac33942b095b759f7a3a3787ebaa73ba65f393
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Mon Dec 7 22:24:42 2020 +0100

    ci: macos: Use libarchive from brew, force links.

    There is a libarchive in the macos installation, and shadowing
    this with our own, brew version is not clear-cut. Link headers
    and libs to /usr/local manually

commit 2394440fbe566b61442f70cfd50df5c6d1101f54
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Mon Dec 7 22:21:41 2020 +0100

    ci: macos: Handle warnings for shallow clone and brew cask

    Log message:
    Error: homebrew-core is a shallow clone. To `brew update` first run:
    git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core"
    fetch --unshallow
    This restriction has been made on GitHub's request because updating shallow
    clones is an extremely expensive operation due to the tree layout and
    traffic of Homebrew/homebrew-core. We don't do this for you automatically
    to avoid repeatedly performing an expensive unshallow operation in CI
    systems (which should instead be fixed to not use shallow clones).

commit 104063741bcbb02f3e8eb910bd75ab7a5a9caa1f
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Mon Dec 7 22:07:31 2020 +0100

    ci: macos: Clean up brew setup and usage.

commit 05790f85377ae361192ca2e731c7bab26fba65e0
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Mon Dec 7 21:54:16 2020 +0100

    ci: Add misssing circle macos build (!).

commit d1ed071a6ab375ce355aa13e7d4d3494aa18759d
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Sat Oct 17 19:06:19 2020 +0200

    docker-auth: fix interpreter path for outdated trusty.

commit 0c2bd57a59b732f306c70c0da0befa6c2a8a0c55
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Sat Oct 17 12:37:33 2020 +0200

    Fix ci/docker-auth.sh permissions.

commit 891f052f04472176a9ecc15f2ed02d7bb01ac9bc
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Sat Oct 17 11:37:54 2020 +0200

    ci: Drop bogus comment.

commit 88b8f0806dcfa375227c8c3985b80d6513ffc652
Author: Alec Leamas <leamas.alec@nowhere.nt>
Date:   Sat Oct 17 11:23:17 2020 +0200

    ci: Add docker authentication (#2050).

    Add script which makes is possible to authenticate before doing docker
    pulls thus avoiding upcoming throttling of unauthenticated pulls.

    Circleci uses direct reference to environment in the configuration file
    to enable authentication.

    Authentication requires an account in docker.io. It is activated by two
    environment variables:

    DOCKER_USER  - the docker.io username
    DOCKER_PW  - the docker.io password

    No agents are configured, password is stored in a cleartext file on builders.

commit e6b6a6b9fa90095bb781a31eedee97612470c163
Author: Alec Leamas <leamas.alec@nowhere.net>
Date:   Sun Oct 4 17:22:00 2020 +0200

    ci: travis: Drop macos builder, use circleci instead.

    The travis builder already runs a lot of jobs. On top of that it's much
    slower than circleci, basically double build time (30 vs 15 minutes)

    Part of the problem is that the travis caching doesn't really work,
    it uploads the new cache in all builds. Net result is that builds
    using a cache is even slower (45 minutes).

commit 895777b5ffa0536007879ac381eb16b252e55787
Author: Alec Leamas <leamas.alec@nowhere.net>
Date:   Sun Oct 4 16:37:29 2020 +0200

    ci:travis: Drop cache.

commit 14e09cd5161295f03aee8b636a490e18ee8d3fc9
Author: Alec Leamas <leamas.alec@nowhere.net>
Date:   Wed Sep 30 21:47:29 2020 +0200

    src: Fix clang compiler warnings.

commit 4751df001bd0cbfa5c47c305d0f686c6407d34ce
Author: Alec Leamas <leamas.alec@nowhere.net>
Date:   Thu Oct 1 14:51:45 2020 +0200

    ci: Drop awful hack for missing pixman dep, comments

commit b99b8792094357a96cf62b63180da21e882b8a1a
Author: Alec Leamas <leamas.alec@nowhere.net>
Date:   Thu Oct 1 21:46:47 2020 +0200

    ci: Add caching of macos deps.

commit cbd01b8fff63a6e38c3448a4eecd1500a6fd1fd8
Author: Alec Leamas <leamas.alec@nowhere.net>
Date:   Thu Oct 1 21:43:29 2020 +0200

    ci: Update macos builder to Xcode 11.0

    Versions lower than 11.0 contains references to dying python2 which
    thus will be removed from Homebrew repos. OTOH, versions like 11.3
    exposes bugs in CPack's bundle generation (unsupported hdi-utils
    commands). Settle for 11.0 for now, the lowest version without
    python2.

commit c04df0e92a01a30a4da20594dce2d6f4c715524f
Author: Alec Leamas <leamas.alec@nowhere.net>
Date:   Thu Oct 1 11:54:22 2020 +0200

    cmake: macos: Fix fixup_bundle permissions problem.

commit fc6b04ffbe73f59bcd258b32cbe3a85f0f5c7609
Author: Alec Leamas <leamas.alec@nowhere.net>
Date:   Thu Oct 1 11:25:27 2020 +0200

    cmake: macos: Add missing deps.

    Make the libraries used by the macos bundle proper dependencies
    so they are picked up when the bundle is genrerated.